BROADVOICE_DATABASE_HOST: '192.168.0.5'
BROADVOICE_DATABASE_PORT: '5432'
BROADVOICE_DATABASE_USER: 'broadvoice'
BROADVOICE_DATABASE_PASSWORD: 'broadvoice'
BROADVOICE_DATABASE_DATABASE: 'broadvoice_dev'